# CI/CD Pipeline for project-unicorn
name: CI/CD Pipeline

# When to trigger this workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define the jobs to run
jobs:
  # Job 1: Build and Test
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Get the code from your repository
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Step 2: Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci
      
    # Step 4: Run linting (code quality check)
    - name: Run linting
      run: npm run lint
      
    # Step 5: Build the application
    - name: Build application
      run: npm run build
      
    # Step 6: Build Docker image (for learning purposes)
    - name: Build Docker image
      run: docker build -t project-unicorn:${{ github.sha }} .
      
  # Job 2: Deploy to Vercel (only on main branch)
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
      
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
    - name: Build Project Artifacts
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
